### ISSUE TITLE
Generated SQL doesn't escape table names

### ISSUE THREAD

**Issue by jasonhildebrand** [WebwareForPython/w4py3-middlekit#2]
Previously, MiddleKit escaped table names in generated SQL (for example in Create.sql), for example:

```
create table `Vendor` (
    vendorId                       int not null primary key auto_increment,
    name                           varchar(100) not null
);
```

Now it does not:

create table Vendor (
    vendorId                       int not null primary key auto_increment,
    name                           varchar(100) not null
);

This may be an issue for schemas which use SQL-reserved words in their table names.

**Comment by jasonhildebrand** [comment]
This was in MySQL - I haven't investigated whether it affects other backends.

**Comment by nlgio** [comment]
Other backends aside from MSSQL are affeccted too, but Klass.sqlTableName definitions stayed unmodified during porting to python3, so  this seems has to be handled as a new non-porting-related issue

**Comment by jasonhildebrand** [comment]
I checked into this further.  It turns out that escaping the table names was a customization we had made to a local copy of MiddleKit in a specific project.  So this is not a regression after all.

It would probably be a reasonable improvement to make, but at this point I think the focus should be on matching the previous (python2) behaviour, not on enhancements.

Closing this issue.
